Add Math constants to Python
source-academy/js-slang pull request #1677
Opened 2024-04-15 16:24 UTC by JJtan2002

2024-04-15 16:31 UTC, RichDom2185 approved these changes

2024-04-15 16:31 UTC, RichDom2185 commented
LGTM, thanks!

2024-04-15 23:31 UTC, martin-henz requested changes
Let's match Python's math library. The constant log10e is not included there. Let's exactly match Python's math library, just like what we do for JavaScript.
```
(base) henz@adminsocs-MacBook-Pro-2 js-slang % python             
Python 3.10.12 (main, Aug  8 2023, 12:44:36) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
>>> from math import (pi)
>>> pi
3.141592653589793
>>> from math import (log10e)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'log10e' from 'math' (/Users/henz/.pyenv/versions/3.10.12/lib/python3.10/lib-dynload/math.cpython-310-darwin.so)
>>> 
```

2024-04-16 01:47 UTC, martin-henz requested changes

2024-04-16 01:47 UTC, martin-henz commented on docs/specs/source_python_math.tex
>  \href{https://www.ecma-international.org/ecma-262/9.0/index.html\#sec-math-object}{\color{DarkBlue}ECMAScript Specification, Section 20.2}. Examples:
Refer to Python documentation here, not to ECMAScript. Make sure that all Python math functions and only the Python math functions are available as math_...

2024-04-16 02:55 UTC, martin-henz requested changes

2024-04-16 02:55 UTC, martin-henz commented on docs/specs/source_python_math.tex
> +\href{https://docs.python.org/3.7/library/math.html}{\color{DarkBlue}Python 3.7.17 Documentation}. Examples:
Don't you want to go for the latest stable release? https://docs.python.org/3/library/math.html

Are you implementing all functions in the Python math library? How about math.isnan, or math.factorial. If any functions are missing, please create an issue where you list what needs to be done to make the implementation consistent with the specs.

2024-04-16 03:57 UTC, martin-henz approved these changes
LGTM

2024-04-16 03:57 UTC, merged