add the comment to link the specification
source-academy/js-slang pull request #1680
Opened 2024-04-16 01:56 UTC by FYL2003

The change is uploaded.

2024-04-16 04:15 UTC, martin-henz requested changes

2024-04-16 04:15 UTC, martin-henz commented on src/stepper/stepper.ts
> +     * push the content into frontend for showing contents in the
This sentence is not complete: "in the" ...

2024-04-16 04:15 UTC, martin-henz commented on src/stepper/stepper.ts
> +     */
This comment "this comment may not be correct" is quite strange. Are you referring to the one above: "push the content..."?

2024-04-16 04:15 UTC, martin-henz commented on src/stepper/stepper.ts
> +     */
If the check is deprecated, please delete it.

2024-04-16 08:32 UTC, RichDom2185 reviewed
Just a minor nit: the comments should be either

```js
// line 1
// line 2
```

or `/* ... */` multi-line comments, not `/** .... */` documentation comments.

2024-09-10 13:13 UTC, martin-henz approved these changes

2024-09-10 13:52 UTC, merged